# Generated by Django 3.1.1 on 2020-11-08 02:47

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('student_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Student_id')),
                ('unh_id', models.IntegerField(blank=True, verbose_name='UNH_id')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('school_email', models.EmailField(max_length=255, verbose_name='School Mail_Id')),
                ('major', models.CharField(max_length=255, verbose_name='Major')),
                ('degree', models.CharField(max_length=255, verbose_name='Degree')),
                ('linkedin', models.CharField(max_length=255, verbose_name='First Name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
