# Generated by Django 3.1.1 on 2020-11-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='linkedin',
            field=models.CharField(max_length=255, verbose_name='Linkedin URL'),
        ),
    ]
