# Generated by Django 3.1.1 on 2020-11-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_data', '0002_auto_20201108_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='unh_id',
            field=models.IntegerField(verbose_name='UNH_id'),
        ),
    ]
