# Generated by Django 3.1.1 on 2020-11-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_data', '0003_auto_20201108_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='unh_id',
            field=models.CharField(max_length=15, verbose_name='UNH_id'),
        ),
    ]
