# Generated by Django 3.1.1 on 2020-11-08 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_data', '0005_internship_internshipassignment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternshipAssignment',
            new_name='Internship_Assignment',
        ),
    ]
