# Generated by Django 3.1.2 on 2020-11-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_data', '0006_auto_20201108_0355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internship_assignment',
            options={'managed': False},
        ),
    ]
