# Generated by Django 3.1.2 on 2020-11-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_data', '0007_auto_20201108_1500'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='internship_assignment',
            table='intern_data_Internship_assignment',
        ),
    ]
