# Generated by Django 3.1.2 on 2020-11-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_data', '0008_auto_20201108_1552'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='internship_assignment',
            table='intern_data_Internship_Assignment',
        ),
    ]
