# Generated by Django 3.1.3 on 2020-11-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='created',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='modified',
        ),
        migrations.AlterField(
            model_name='internship',
            name='internship_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='internship',
            name='organization_address',
            field=models.CharField(max_length=255, verbose_name='Mailing Address'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='organization_name',
            field=models.CharField(max_length=255, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='organization_url',
            field=models.CharField(max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='pay',
            field=models.CharField(max_length=7, null=True, verbose_name='Pay'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Internship Position'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='supervisor_email',
            field=models.CharField(max_length=255, null=True, verbose_name='Supervisor Email'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='supervisor_name',
            field=models.CharField(max_length=255, verbose_name='Supervisor Name'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='supervisor_phone',
            field=models.CharField(max_length=100, null=True, verbose_name='Supervisor Phone'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='supervisor_position',
            field=models.CharField(max_length=255, null=True, verbose_name='Supervisor Position'),
        ),
    ]
