# Generated by Django 3.1.2 on 2020-11-14 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship_assignment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='internship_assignment',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created',
        ),
        migrations.RemoveField(
            model_name='student',
            name='modified',
        ),
    ]
