# Generated by Django 3.1.2 on 2020-11-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_auto_20201114_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Student_id'),
        ),
    ]
