# Generated by Django 3.1.2 on 2020-11-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_auto_20201114_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='unh_id',
            field=models.CharField(max_length=15, unique=True, verbose_name='UNH_id'),
        ),
    ]
