# Generated by Django 3.1.3 on 2020-11-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_auto_20201116_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='unh_id',
            field=models.CharField(max_length=255, verbose_name='UNH_id'),
        ),
    ]
