# Generated by Django 3.1.3 on 2020-11-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_auto_20201116_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='internship_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Internship_Id'),
        ),
    ]
