# Generated by Django 3.1.3 on 2020-11-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_auto_20201116_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_assignment',
            name='end_date',
            field=models.CharField(max_length=36, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='internship_assignment',
            name='start_date',
            field=models.CharField(max_length=36, verbose_name='Start Date'),
        ),
    ]
